
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/vollmed_api
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never